title: Lei Yao(姚磊)
position: Master of Electronic Information
affiliation: School of Physics, Northeast Normal University
email: yaolei@nenu.edu.cn
email_link: mailto:yaolei@nenu.edu.cn
github_link: https://github.com/leiyao1299
weixin: ./assets/img/weixin.png
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description:  A Master of Electronic Information at the School of Physics, Northeast Normal University (NENU)
remote_theme: yaoyao-liu/strata-academic
